### ISSUE TITLE
Can we hide Azure API Authentication Key?

### ISSUE THREAD

**Issue by HarshadPatel1988** [MicrosoftTranslator/DocumentTranslator#24]
Hi Team,

Can we have a feature of hiding azure API authentication key, after it set in document translator? This will help us to keep key secured with us and users can not have access to it directly from settings tab.

**Comment by chriswendt1** [comment]
Yes, we can make the field a password field.

**Comment by HarshadPatel1988** [comment]
Thanks Chris,

Can you please make this change in next release if possible?

**Comment by mbalcerzyk** [comment]
Dear Chris. 
I have just translated a document with version 1.2 successfully.  Then I installed version 1.3.1 with Azure, because this is not UWP app which is installed and managed by the Store. It had lost my subscription, but the subscription page in Settings at https://www.microsoft.com/en-us/translator/getstarted.aspx does not open anything. I am in Spain, and here it seems Microsoft forces opening /es-es/ pages. Microsoft.com opens in Spanish.
**Cannot the service be bound to Microsoft account (private or work) somehow?**. It would solve the problem of registering the copy on each computer separately.
Meanwhile I cannot use Document Translator, because of registration problem on one of my PCs. Could you please help to get back Document Translator. 
Regards 
Marcin

**Comment by chriswendt1** [comment]
@HarshadPatel1988: The Key is hidden in the UI now, as of version 1.3.2, applying the PasswordBox XAML control. 
@mbalcerzyk: Please create a subscription at portal.azure.com. You can use our forum at http://aka.ms/translatorsupport for subscription support. That works better than here on GitHub. And faster.
The Translator API supports app authentication, not user authentication. The app then controls user authentication. Document Translator does not perform user authentication.

**Comment by HarshadPatel1988** [comment]
Thanks Chris for the fix. By what time the new release build will be available for download?

**Comment by chriswendt1** [comment]
It is now.

**Comment by HarshadPatel1988** [comment]
Thanks Chris,

Just downloaded latest build, will let you know if found any issues during testing, Which I am sure is not going to be the case :)

**Comment by chriswendt1** [comment]
The build 1.3.2 wasn't working, I removed it. Fixed now in 1.3.3. Please download again.
