### ISSUE TITLE
please add translate multi text in one request method.

### ISSUE THREAD

**Issue by qinxiaowen** [MicrosoftTranslator/DocumentTranslator#68]
I want to translator 10 sentence ,but i don't want request 10 request.
so  i found API found the **request texttype** must  is plain or html.
i think should add like 'json' type.i don't think the behavior can reduce the service  income .
because i can do exactly that use html type to simulation the requirement.
thanks .

**Comment by chriswendt1** [comment]
The native format of the Translator V3 API is JSON. Requests are JSON, and responses are delivered in JSON. Translator uses its own JSON format definition. 
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate?tabs=curl#request-body
It is questionable whether you want to offer a translation function for arbitrary JSON objects, because the object has no intrinsic markup for what needs translation and what doesn't. You could easily write one that translates everything though. Is that what you are looking for?
